version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: my-mariadb
    ports:
      - "3307:3307"
    environment:
      - MARIADB_ROOT_PASSWORD=1234
      - MARIADB_DATABASE=memo_db
      - MARIADB_USER=memo_user
      - MARIADB_PASSWORD=memo_pass
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
