spring:
  application:
    name: toy_back_end
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/memo_db
    username: memo_user
    password: memo_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
